### ISSUE TITLE
Pull docker ROS image.

### ISSUE THREAD

**Issue by BearCatMicro** [BearCatMicro/DockerizeROS#1]
We already have docker installed on the machine.
The next things is to get a docker images from the docker repository of ROS https://hub.docker.com/_/ros.

We need the image `ros:indigo-ros-core-xenial`.

To do this you may enter command 
`docker pull ros:indigo-ros-base-xenial`

+ indigo means the version of ROS that we want to use is **indigo**
+ xenial means the version of OS that we want to use is Ubuntu Xenial (16.04)
+ ros-base means we only want to have the simlest ros images. By using this, we cant analyze all the dependencies that the HCR needs and documents it.

Any question on this?

**Comment by embengoibo** [comment]
1. Run: $ docker pull ros:indigo-ros-base-xenial
Error response from daemon: manifest for ros:indigo-ros-base-xenial not found: manifest unknown: manifest unknown
2. Run:  $ docker pull ros:indigo-ros-base
OK

--> It seems that ROS indigo not supports for Xenial ?

**Comment by BearCatMicro** [comment]
We gonna check this later. I remember that yesterday, I'm still be able to pull the xenial image.

**Comment by embengoibo** [comment]
Have checked with this command:
$ docker image ls -a

There are no image ros:indigo-ros-base-xenial as well, please check again when we meet

**Comment by BearCatMicro** [comment]
I think there must be some images with `xenial`

The right command is `docker images -a`. `ls` options is not available for `docker images` command

**Comment by embengoibo** [comment]
Yes, there is an image related to xenial
`kinetic-perception-xenial   2d3c348497c0        9 days ago          2.31GB`
Can we use it?

**Comment by BearCatMicro** [comment]
that image using ros kinetic version. 
So let's see if we can do somethings, but for now just keep using indigo-ros-base.

**Comment by BearCatMicro** [comment]
I think we can create the image later by building a new images using ubuntu xenial and install ros indigo on it.

In the end we will packedup everything as an docker file, using this docker file anyone from anyplace will be able to build our customized ros images.
