### ISSUE TITLE
Make ROS container running

### ISSUE THREAD

**Issue by BearCatMicro** [BearCatMicro/DockerizeROS#3]
Usually, when calling command  `docker run` to run a container. It will executed a script called entry point. When this script finished, the container will exit and go to the state `exited`.

To prevent this behavior, there is two things we can do. But in this issue we will look into the easy way first.

So after you have already call `docker run --name rosbuild ros:indigo-ros-base-xenial`, we're having a container named `rosbuild` at the moment.

Now to start it from `exited` state to `running` state, you should call this command `docker start rosbuild`.

After that check if the container is in running state or not using `docker container ps -a`.

If it is in running state, the next step is to access into the container by executing this command 
`docker exec -it rosbuild /bin/bash` 

This command will execute the /bin/bash program inside the container rosbuild, because we have specify the `-it` options, the /bin/bash will create a new shell session and connect you to it though a tty.

This prevent the container from exiting.

**Comment by embengoibo** [comment]
I tried to use 
$ docker start rosbuild 
It seems that the container still exited after some seconds. Then I obviously cannot move to the next step, please review

**Comment by embengoibo** [comment]
`qnguyen@qnguyen-pc:~$ docker start rosbuild
rosbuild
qnguyen@qnguyen-pc:~$ docker container ls -a
CONTAINER ID        IMAGE                 COMMAND                  CREATED             STATUS                     PORTS               NAMES
55c31e4897f2        ros:indigo-ros-base   "/ros_entrypoint.sh …"   12 minutes ago      Exited (0) 4 seconds ago                       rosbuild
qnguyen@qnguyen-pc:~$ docker start rosbuild
rosbuild
qnguyen@qnguyen-pc:~$ docker container ls -a
CONTAINER ID        IMAGE                 COMMAND                  CREATED             STATUS                    PORTS               NAMES
55c31e4897f2        ros:indigo-ros-base   "/ros_entrypoint.sh …"   12 minutes ago      Exited (0) 1 second ago                       rosbuild
qnguyen@qnguyen-pc:~$ docker exec -it rosbuild /bin/bash
Error response from daemon: Container 55c31e4897f2adffa96429e5e47daf7712d1ddadfd832a9097dec3e646e6c3f6 is not running
qnguyen@qnguyen-pc:~$ 
`

**Comment by embengoibo** [comment]
> qnguyen@qnguyen-pc:~$ docker start rosbuild
> rosbuild
> qnguyen@qnguyen-pc:~$ docker container ls -a
> CONTAINER ID        IMAGE                 COMMAND                  CREATED             STATUS                     PORTS               NAMES
> 55c31e4897f2        ros:indigo-ros-base   "/ros_entrypoint.sh …"   12 minutes ago      Exited (0) 4 seconds ago                       rosbuild
> qnguyen@qnguyen-pc:~$ docker start rosbuild
> rosbuild
> qnguyen@qnguyen-pc:~$ docker container ls -a
> CONTAINER ID        IMAGE                 COMMAND                  CREATED             STATUS                    PORTS               NAMES
> 55c31e4897f2        ros:indigo-ros-base   "/ros_entrypoint.sh …"   12 minutes ago      Exited (0) 1 second ago                       rosbuild
> qnguyen@qnguyen-pc:~$ docker exec -it rosbuild /bin/bash
> Error response from daemon: Container 55c31e4897f2adffa96429e5e47daf7712d1ddadfd832a9097dec3e646e6c3f6 is not running
qnguyen@qnguyen-pc:~$

**Comment by BearCatMicro** [comment]
it seem that the ros_entrypoint.sh script, which came from the images is not working stable.
You could try to stop and remove the container with the following commands
`docker container stop rosbuild`
`docker container rm rosbuild`

Then rerun the container with some specific flags
`docker run --name rosbuild -t -d ros:indigo-ros-base`

**Comment by embengoibo** [comment]
Everything is fine now. The command works perfectly: `docker run --name rosbuild -t -d ros:indigo-ros-base` 
The target of this issue is to keep the container running. It is done now. If there is nothing to investigate here. We can close it?

**Comment by BearCatMicro** [comment]
We will close this issue I will create a new issue for prevent the container to auto-exit
