### ISSUE TITLE
Copy HCR workspace into container

### ISSUE THREAD

**Issue by BearCatMicro** [BearCatMicro/DockerizeROS#4]
Now we have an ROS container running, the next step is to copy the HCR workspace over the container.

You may see the HCR workspace on the host in path /home/qnguyen/HCR/
Please `cd /home/qnguyen/HCR` and in this place you can use the command 
`zip -r ws_hcr.zip ws_hcr/` to zip the whole workspace directory for easy transfer.

To copy this zip file to the `running` container, you can uses the following command
`docker cp ws_hcr.zip rosbuild:/root/`

**Comment by embengoibo** [comment]
I have a quick question, sometime you used tar, sometime you used zip? Do you have a mean for it?

**Comment by embengoibo** [comment]
1. Zip file 
2. Used command `docker exec -it rosbuild /bin/bash/`
3. cd root -> ls -> Check file
4. ws_hcr.zip here! :+1:

**Comment by BearCatMicro** [comment]
Linux or other Unix base OS usually come with `tar` built-in
Some OS may requires you to install zip utilities.

Docker images is a stripped, minimal version of an OS, so I always expect that it will not have zip or any extra tools. So I will use `tar` if the file I have to process comes with `tar` extension, or just because I#m not sure that zip is available on the system or not.

In this case I known zip is available for sure.

I love zip because of is simplicity.
